// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword.Outputs
{

    [OutputType]
    public sealed class GetOnepasswordItemSectionResult
    {
        public readonly ImmutableArray<Outputs.GetOnepasswordItemSectionFieldResult> Fields;
        public readonly string Id;
        public readonly string Label;

        [OutputConstructor]
        private GetOnepasswordItemSectionResult(
            ImmutableArray<Outputs.GetOnepasswordItemSectionFieldResult> fields,

            string id,

            string label)
        {
            Fields = fields;
            Id = id;
            Label = label;
        }
    }
}
